name: rsda
markdown: kramdown
collections:
  artifacts:
    output: true
    permalink: /artifacts/:path/
  authors:
    output: true
    permalink: /authors/:path/
  origins:
    output: true
    permalink: /origins/:path/
  years:
    output: true
    permalink: /years/:path/
  types:
    output: true
    permalink: /types/:path/
  tags:
    output: true
    permalink: /tags/:path/